wandb_version: 1

_wandb:
  desc: null
  value:
    python_version: 3.12.3
    cli_version: 0.17.4
    framework: huggingface
    huggingface_version: 4.43.3
    is_jupyter_run: true
    is_kaggle_kernel: false
    start_time: 1728607787
    t:
      1:
      - 1
      - 2
      - 3
      - 5
      - 11
      - 49
      - 53
      - 55
      - 71
      - 105
      2:
      - 1
      - 2
      - 3
      - 5
      - 11
      - 49
      - 53
      - 55
      - 71
      - 105
      3:
      - 23
      4: 3.12.3
      5: 0.17.4
      6: 4.43.3
      8:
      - 1
      - 4
      - 5
      13: darwin-arm64
